### ISSUE TITLE
The register machine simulator doesn't work, due to occurrences of "@xxx" in the code.

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/sicp#591]
Try any of the examples in [Section 5.2](https://sourceacademy.org/sicpjs/5.2).  You'll get the following when you attempt to run them
```
Line 89: SyntaxError: Unexpected character '@' (89:0)
```

Then if you check the code you will see the string `@xxx` there and a bunch of other places.

**Comment by ngxingyu** [comment]
Hi, I suspect this issue is still present. I still observe @xxx in the following chapters (refer below). I took a look at the codeArr variable, and observed that `@xxx` often occurs without the trailing newline character, so that might be the issue. e.g. in https://sourceacademy.org/sicpjs/5.2.3
```
[
  '\nfunction op(name) { return list("op", name); }\n',
  '@xxx',
  '\n' +
    'function is_operation_exp(exp) {\n' +
    '    return is_pair(exp) && is_tagged_list(head(exp), "op");\n' +
    '}\n',
  '@xxx',
  '\nfunction operation_exp_op(op_exp) { return head(tail(head(op_exp))); }\n',
  '@xxx',
  '\nfunction operation_exp_operands(op_exp) { return tail(op_exp); }\n\t  '
]
```

```
2.1.3.json
2.4.2.json
2.4.3.json
3.1.3.json
3.1.3.json
2.5.2.json
2.3.2.json
5.2.3.json
4.1.3.json
4.1.2.json
2.3.3.json
2.3.3.json
3.3.2.json
4.2.2.json
5.4.4.json
1.2.2.json
2.2.2.json
3.5.1.json
3.3.4.json
3.3.1.json
2.3.4.json
2.5.3.json
4.1.5.json
5.4.2.json
2.4.1.json
1.1.6.json
5.5.2.json
3.4.2.json
2.5.1.json
4.4.4.json
4.1.4.json
2.1.1.json
```

**Comment by samuelfangjw** [comment]
> Hi, I suspect this issue is still present. I still observe @xxx in the following chapters (refer below). I took a look at the codeArr variable, and observed that `@xxx` often occurs without the trailing newline character, so that might be the issue. e.g. in https://sourceacademy.org/sicpjs/5.2.3

Thanks @ngxingyu for looking into this!

**Comment by mark-friedman** [comment]
>Hi, I suspect this issue is still present. I still observe @xxx in the following chapters (refer below). I took a look at the codeArr variable, and observed that @xxx often occurs without the trailing newline character, so that might be the issue. e.g. in https://sourceacademy.org/sicpjs/5.2.3

I'm not sure that the existence of the `@xxx` in the JSON is a problem in and of itself.  For example, when I look at the code in the embedded playgrounds in https://sourceacademy.org/sicpjs/5.2.3 I don't see any `@xxx`s.

I'm not an expert on the SICP code, but I believe that there is some processing of the code from the JSON which replaces the `@xxx`s.  For my original issue, I believe that the problem was that that processing wasn't always happening correctly and that, I believe, was fixed by #592.  Of course that doesn't mean that there aren't still any other issues with `@xxx`s!

**Comment by ngxingyu** [comment]
> >Hi, I suspect this issue is still present. I still observe @xxx in the following chapters (refer below). I took a look at the codeArr variable, and observed that @xxx often occurs without the trailing newline character, so that might be the issue. e.g. in https://sourceacademy.org/sicpjs/5.2.3
> 
> I'm not sure that the existence of the `@xxx` in the JSON is a problem in and of itself.  For example, when I look at the code in the embedded playgrounds in https://sourceacademy.org/sicpjs/5.2.3 I don't see any `@xxx`s.
> 
> I'm not an expert on the SICP code, but I believe that there is some processing of the code from the JSON which replaces the `@xxx`s.  For my original issue, I believe that the problem was that that processing wasn't always happening correctly and that, I believe, was fixed by #592.  Of course that doesn't mean that there aren't still any other issues with `@xxx`s!

I still see the `@xxx` in a few of the code snippets e.g. https://sourceacademy.org/sicpjs/5.2.3 or https://sourceacademy.org/sicpjs/1.1.6#ex-1.4
![Screenshot_20210807-082328_Chrome.jpg](https://user-images.githubusercontent.com/12682160/128581892-5472c62f-c664-44c3-b1fa-a3df6127c3ea.jpg)

**Comment by mark-friedman** [comment]
> I still see the `@xxx` in a few of the code snippets e.g. https://sourceacademy.org/sicpjs/5.2.3#p11 or https://sourceacademy.org/sicpjs/1.1.6#ex-1.4

Indeed you are right!  So there are still some `@xxx` related issues.

**Comment by samuelfangjw** [comment]
This should be fixed properly now (might require a hard refresh). Thanks @mark-friedman and @ngxingyu for raising this issue!

<img width="812" alt="Screenshot 2021-08-08 at 7 23 35 AM" src="https://user-images.githubusercontent.com/60355570/128616172-34918dab-f41f-422a-bdf0-c1df4546a3e4.png">
